name: my_symptom_checker_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  http: ^1.3.0
  path: ^1.9.1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1  # Match teammate’s version if needed
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  table_calendar: ^3.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/ 
    - assets/HealthMate2.PNG
    - assets/healthMateLogo.PNG
    - assets/back.PNG
    - assets/flowers.PNG
    - assets/talkingflower.PNG
    - assets/talkingflower2.PNG
    - assets/blackHair1.png
    - assets/blackHair2.png
    - assets/blondeHair1.png
    - assets/blondeHair2.png
    - assets/blueBackground.png
    - assets/brownHair1.png
    - assets/brownHair2.png
    - assets/cuteHairBlack.png
    - assets/cuteHairBlonde.png
    - assets/cuteHairRed.png
    - assets/faceBlush.png
    - assets/faceCute.png
    - assets/faceElated.png
    - assets/faceSmile.png
    - assets/faceSmirk.png
    - assets/greenBackground.png
    - assets/head1.png
    - assets/head2.png
    - assets/head3.png
    - assets/pigtailsBlonde.png
    - assets/pigtailsBrown.png
    - assets/pigtailsRed.png
    - assets/pinkBackground.png
    - assets/purpleBackground.png
    - assets/redBackground.png
    - assets/redHair1.png
    - assets/redHair2.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
